#:schema node_modules/wrangler/config-schema.json
name = "appzap-diy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-10-30"
pages_build_output_dir = "./build/client"

# These variables are available to the build process as plain text.
# ONLY public keys should be here.
[vars]
VITE_SUPABASE_URL = "https://dpebpgvwkawspwbcaahr.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZWJwZ3Z3a2F3c3B3YmNhYWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MDkzMDksImV4cCI6MjA3NzQ4NTMwOX0.SDITQYCAQtIVGouCviJu2Ih06wHpOgZKMAHcyBUFmG4"
VITE_PUBLIC_APP_URL = "https://appzap.co"

 

 